spring.application.name=couponmoa-common
spring.profiles.active=local

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=env,beans
management.endpoint.health.show-details=always
management.server.port=8081

org.jobrunr.dashboard.enabled=true
org.jobrunr.background-job-server.enabled=true
org.jobrunr.jobs.metrics.enabled=true
org.jobrunr.dashboard.port=8000

spring.cache.type=redis
spring.cache.redis.time-to-live=900000